### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Haeherfeder**
may also change the name of the file.

### CODE REVIEW

**Comment by Haeherfeder** [comment]
I did not find where the help messages are located, so i cant change them to say that it now uses san

**Comment by NexInfinite** [comment]
https://github.com/NexInfinite/chess/blob/master/Cog/help.py This is the help command, is this what you've changed?

**Comment by Haeherfeder** [comment]
> https://github.com/NexInfinite/chess/blob/master/Cog/help.py This is the help command, is this what you've changed?

I think somewhere is explained that a move look like "rock, a6", but this would now be "Ra6" (if there is only one Rock that can move there). you could also use "Ra8-a7" (I think, maybe without the -)
like written here (https://www.fide.com/FIDE/handbook/LawsOfChess.pdf (Appendices C, site 18))

**Comment by Haeherfeder** [comment]
?

**Comment by NexInfinite** [comment]
Sorry for the delay, didn't get a notification about your last message. So you've changed the syntax so `Ra6` would work instead of `Rook, a6`, assuming rook can move to a6?

**Comment by Haeherfeder** [comment]
> Sorry for the delay, didn't get a notification about your last message. So you've changed the syntax so `Ra6` would work instead of `Rook, a6`, assuming rook can move to a6?

Yes

**Comment by NexInfinite** [comment]
Yeah just checked over what you've done, liking the function for the check. I'll pull now, don't see any issues from a glance.

**Comment by Haeherfeder** [comment]
> Yeah just checked over what you've done, liking the function for the check. I'll pull now, don't see any issues from a glance.

okay, thanks

**Pull request merged**
